#기본이여서 생략됨, 없어도 지장없음 다만 바꿀수 있다.
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    url: jdbc:mariadb://localhost:3307/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234

  #테이블 자동생성 : true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  #서버 설정 : 구글메일 보통 포트 : 587, 인텔리제이에서 smtp이하 부분 빨간색으로 나오지만 정상작동함.
  mail:
    host: smtp.gmail.com
    port: 587
    username: rkdrudrn1031@gmail.com
    password: wplkdkdvjwgbppps
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    root: info

mybatis:
  #xml 위치
  mapper-locations: mybatis/**/*.xml
  configuration:
    #DB 소문자 스네이크 표기된 부분 자동으로 카멜로 바꾸어줌.
    map-underscore-to-camel-case: true
    #standartout 화면에 바로 log로 표시.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

